### ISSUE TITLE
Pod Network Policy Block

### ISSUE THREAD

**Issue by HacksonClark** [SREGym/SREGym#44]
- Fault: Apply a `NetworkPolicy` that disallows ingress/egress to/from critical services.    
- Effect: Service is "up" but cannot receive traffic.
- Fix: Patch or delete network policy.

Example:

```yaml
# Deny all egress from cartservice
kind: NetworkPolicy
spec:
  podSelector:
    matchLabels:
      app: cartservice
  policyTypes:
    - Egress
```
