### ISSUE TITLE
Readiness/Liveness Probe Misconfiguration

### ISSUE THREAD

**Issue by HacksonClark** [SREGym/SREGym#50]
- Fault: Set a liveness probe path that 404s or fails healthcheck.
    
- Effect: Kubernetes continuously restarts healthy pods.
    
- Fix: Patch the probe to point to correct endpoint (e.g., `/healthz`, `/ping`).
  
Example:

```yaml
livenessProbe:
  httpGet:
    path: /wrong
    port: 8080
```
