### ISSUE TITLE
Toleration Without Matching Taint

### ISSUE THREAD

**Issue by HacksonClark** [SREGym/SREGym#55]
- Fault: Taint a node (`NoSchedule`) but forget to add the toleration to a pod.
    
- Effect: Pod won’t get scheduled.
    
  ```bash
  kubectl taint node worker1 key=value:NoSchedule
  ```

Example:

- Fix: Patch pod to add:
    ```yaml
    tolerations:
    - key: "key"
      operator: "Equal"
      value: "value"
      effect: "NoSchedule"
    ```
