### ISSUE TITLE
Resource Requests Too Large

### ISSUE THREAD

**Issue by HacksonClark** [SREGym/SREGym#56]
- Fault: Set CPU/memory requests that no node can satisfy.

Example:
    ```yaml
    resources:
      requests:
        memory: "64Gi"
    ```
    
- Effect: Stuck `Pending`, error like:
    
    ```
    0/3 nodes available: Insufficient memory
    ```
    
- Fix: Lower the resource requests.
